### ISSUE TITLE
Remove "Personal" checklist

### ISSUE THREAD

**Issue by dominikbohm** [mohitbagra/vsts-extensions-checklist#1]
Hello, 

is it possible to completely remove the "Personal" checklist tab? I would like to use only the "Shared" tab. It would be best if I could remove the tab list completely and define only Shared checklist (without the label "Shared").

Thank you for your answer.

**Comment by mohitbagra** [comment]
Thanks for your feedback, I will look into this.

**Comment by KaiGutzeit** [comment]
Hello Mohit, 

the same request from our side. Would be great to completely remove the Personal checklist Tab, or just change the order. The main reason is, that the checklist should be mainly a tool used by Projectmanagers, to create some kind of "Subtasks" for a certain work item, the personal tab could be still used, but the shared on should be the prio Checklist Tab.

Would be great to have this feature implemented soon :)

**Comment by KaiGutzeit** [comment]
![image](https://user-images.githubusercontent.com/11773466/35139559-f58ae434-fcf3-11e7-8fea-b87b8382d263.png)

**Comment by mohitbagra** [comment]
This has been in my radar but I havent been able to give enough time to this till now. I'll get to this at some point hopefully by next month. Sit tight :)

**Comment by mohitbagra** [comment]
@KaiGutzeit @dominikbohm  I have made a few updates in the extension. The "Shared" view is now the default view. I am planning to add some more customizations so that users can disable Personal checklist for a work item type and be able to pre-define some shared checklist items.

**Comment by KaiGutzeit** [comment]
@mohitbagra great work, this is exactly what we have needed. One little thing: As you have added the new "mandatory" option. Could you maybe set this information to the default option when you add a new Element to the checkbox list? I would say generally, you would not put to the checklist any Checkbox Task, which is not mandatory if this is the case, you could then set then explicitly the mandatory option to false.

**Comment by mohitbagra** [comment]
@KaiGutzeit  Done

**Comment by KaiGutzeit** [comment]
@mohitbagra that was quick, works perfectly. Thank you 👍
