### ISSUE TITLE
Question : Download for TFS On Prem

### ISSUE THREAD

**Issue by rudywilkjr** [mohitbagra/vsts-extensions-checklist#3]
Is there a way we can download and integrate this extension to an on-premises installation of TFS 2015?

Thanks!!

**Comment by mohitbagra** [comment]
I dont think so. The support for new extensions in Work item form only came in TFS 2017. So you'll need atleast that.

**Comment by rudywilkjr** [comment]
Got it. Thanks for following up.

Our migration to vsts can't occur fast enough! :)
