### ISSUE TITLE
Move checklist to an added page

### ISSUE THREAD

**Issue by rlheman** [mohitbagra/vsts-extensions-checklist#5]
Would it be possible to have the checklist movable?  I'd like to use it on a custom page instead of on the details page.  The checklist I have is very long and takes up too much space on the user story details page. I created a new page for the checklist but can't move it from the details page to the new page.  

Thanks,
Randi

![image](https://user-images.githubusercontent.com/19841542/36986789-f0a83dea-2057-11e8-8c6e-7318fc3d73f8.png)

![image](https://user-images.githubusercontent.com/19841542/36986887-3b0495a0-2058-11e8-985b-0c65034e98d6.png)

**Comment by mohitbagra** [comment]
Yes you can. From the process admin page -
1.  Click on the ellipsis menu on Checklist extension
2. Click on the "Edit" from the context menu on Checklist extension to open the edit dialog
![image](https://user-images.githubusercontent.com/3766956/36993667-87f4b9ac-207c-11e8-84a8-f80bc822dc67.png)

3. From the dialog, pick your new "page"
![image](https://user-images.githubusercontent.com/3766956/36993721-b79cfebc-207c-11e8-9c47-a6c89855bf99.png)

**Comment by mohitbagra** [comment]
@rlheman  Did this answer your question?
